name: Create Alfred Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Build wsaw
        run: go build -o wsaw
      - name: Build Alfred workflow
        id: builder
        uses: almibarss/build-alfred-workflow@v1
        with:
          workflow_dir: .
          exclude_patterns: '!*.alfredworkflow !wsaw'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.builder.outputs.workflow_file }}