name: Create Alfred Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        go: [ '1.19' ]
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: Build wsaw
        run: go build -o wsaw
      - name: Build Alfred workflow
        id: builder
        uses: almibarss/build-alfred-workflow@v1
        with:
          workflow_dir: .
          exclude_patterns: '.git .github .gitignore go.mod go.sum main.go README.md' # 无法反选，只能列举除了wsaw和alfredworkflow以外的所有文件
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.builder.outputs.workflow_file }}